# Generated by Django 5.0.1 on 2024-01-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('sclass', models.CharField(max_length=100)),
                ('dname', models.CharField(max_length=100)),
            ],
        ),
    ]
