# Generated by Django 5.0.1 on 2024-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_details',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
